const 支部情况 = [
  {
    searchValue: null,
    uid: "1737652057429606402",
    creatorUid: "1731907755384500226",
    createTime: "2023-12-21 09:51:49",
    updaterUid: "1731907755384500226",
    updateTime: "2023-12-21 09:51:49",
    params: {},
    orgId: "347",
    orgName: "锦诚总支部",
    count: null,
    introduce:
      "党总支书记  总经理 蒋友银\n工作分工及责任：\n1、认真贯彻执行党的路线方针政策和上级党组织的决议。\n2、全面负责党建工作。\n3、全面负责总支党风廉政建设工作。\n4、组织总支工作，明确总支年度重点工作，督促有效推\n进。\n5、负责召集党员大会、总支委会。\n6、组织中心组学习。\n7、选配好适任干部，把好干部选任的程序和标准，负责\n干部队伍建设和组织发展工作，做好后备干部的选拔、培养工作。\n8、负责党建带群建，加强党总支对工会、共青团工作的领导。\n9、围绕企业改革发展开展调查研究，开展经常性的思想政治工作，保持职工队伍稳定。\n党总支副书记（分管纪检工作）、工会主席 金蕾\n工作分工及责任：\n1、总支书记不在时，由总支副书记主持总支的日常工作。\n2、协助总支书记做好干部管理和组织发展工作。\n3、协助总支书记开展党员的管理工作，了解掌握党员的\n思想、工作和学习情况。\n4、协助总支书记抓好党组织与群团组织的密切联系，充分调动群众的积极性。\n5、协助总支书记做好党风廉政建设四责协同机制建设。\n党总支委员（分管组织工作）、副总经理 施悦勤\n工作分工及责任：\n1、负责党支部和党员队伍信息的管理、党组织关系转接、\n党费收缴、使用管理。\n2、具体负责指导党组织换届、党员发展工作。\n3、督促各支部按要求开展“三会一课”、主题党日活动。\n4、协助总支书记做好支部工作考核。\n党总支委员（分管宣传工作）、总经理助理  刘洋\n工作分工及责任：\n1、\t协助总支书记开展党员的教育工作，提出党员教育培\n训计划。\n2、提出宣传工作意见，负责目视化管理、党建网评论等。\n3、围绕公司的中心工作，开展多种形式的宣传教育活动。\n4、配合群团组织，搞好企业文化建设。\n党总支委员（分管群团工作）、综合办副主任（主持工作）、 工会副主席 钱佳英\n工作分工及责任：\n1、\t引导工会组织和共青团组织围绕党的中心工作，结合\n特点开展活动。\n2、\t联系干部职工，了解思想动态，有针对性地做好思想\n政治工作。\n3、指导协助工会组织和共青团组织做好推优入党工作。\n4、指导党建带工建、党建带团建工作。党总支书记  总经理 蒋友银\n工作分工及责任：\n1、认真贯彻执行党的路线方针政策和上级党组织的决议。\n2、全面负责党建工作。\n3、全面负责总支党风廉政建设工作。\n4、组织总支工作，明确总支年度重点工作，督促有效推\n进。\n5、负责召集党员大会、总支委会。\n6、组织中心组学习。\n7、选配好适任干部，把好干部选任的程序和标准，负责\n干部队伍建设和组织发展工作，做好后备干部的选拔、培养工作。\n8、负责党建带群建，加强党总支对工会、共青团工作的领导。\n9、围绕企业改革发展开展调查研究，开展经常性的思想政治工作，保持职工队伍稳定。\n党总支副书记（分管纪检工作）、工会主席 金蕾\n工作分工及责任：\n1、总支书记不在时，由总支副书记主持总支的日常工作。\n2、协助总支书记做好干部管理和组织发展工作。\n3、协助总支书记开展党员的管理工作，了解掌握党员的\n思想、工作和学习情况。\n4、协助总支书记抓好党组织与群团组织的密切联系，充分调动群众的积极性。\n5、协助总支书记做好党风廉政建设四责协同机制建设。\n党总支委员（分管组织工作）、副总经理 施悦勤\n工作分工及责任：\n1、负责党支部和党员队伍信息的管理、党组织关系转接、\n党费收缴、使用管理。\n2、具体负责指导党组织换届、党员发展工作。\n3、督促各支部按要求开展“三会一课”、主题党日活动。\n4、协助总支书记做好支部工作考核。\n党总支委员（分管宣传工作）、总经理助理  刘洋\n工作分工及责任：\n1、\t协助总支书记开展党员的教育工作，提出党员教育培\n训计划。\n2、提出宣传工作意见，负责目视化管理、党建网评论等。\n3、围绕公司的中心工作，开展多种形式的宣传教育活动。\n4、配合群团组织，搞好企业文化建设。\n党总支委员（分管群团工作）、综合办副主任（主持工作）、 工会副主席 钱佳英\n工作分工及责任：\n1、\t引导工会组织和共青团组织围绕党的中心工作，结合\n特点开展活动。\n2、\t联系干部职工，了解思想动态，有针对性地做好思想\n政治工作。\n3、指导协助工会组织和共青团组织做好推优入党工作。\n4、指导党建带工建、党建带团建工作。",
    imgUrl: "https://p0.ssl.qhmsg.com/t01da1e4ef25adfd30a.jpg",
    ossId: "1737651342074281985",
    minOssId: null,
    isActive: "1",
  },
  {
    searchValue: null,
    uid: "1706931487027220481",
    creatorUid: "418",
    createTime: "2023-09-27 15:19:14",
    updaterUid: "418",
    updateTime: "2023-09-27 15:19:14",
    params: {},
    orgId: "493",
    orgName: "机关资产财务部党支部",
    count: null,
    introduce:
      "资产财务部党支部共有党员11名，其中男党员3名，女党员8名。支部党员中有党员领导干部4人，具有高级职称5人，具有中级职称4人。具有研究生学历3人，在读研究生2人，本科学历5人，专科学历1人。\n支部委员会由党支部书记、支部宣传委员、支部组织委员组成。\n资产财务部党支部在集团公司党委的坚强领导下，在以习近平新时代中国特色社会主义思想指导下，全面贯彻落实习近平总书记关于把上海港“建设好、管理好、发展好”的殷殷嘱托，深入学习贯彻党的二十大精神，深刻认识“两个确定”、牢固树立“四个意识”、坚持“四个自信”，做到“两个维护”，努力建设一支风清气正、心齐劲足、团结协作、服务高效、融合发展，具有凝聚力和战斗力的先锋党员队伍。",
    imgUrl: "https://p0.ssl.qhmsg.com/t01da1e4ef25adfd30a.jpg",
    ossId: null,
    minOssId: null,
    isActive: "1",
  },
];

const 党支部委员名单 = [
  {
    searchValue: null,
    uid: "1747471447339683842",
    creatorUid: "103",
    createTime: "2024-01-17 12:10:34",
    updaterUid: "103",
    updateTime: "2024-01-17 12:10:34",
    params: {},
    memberName: "郭明",
    orgId: "60",
    orgName: "明东公司工程技术部党总支-工程部设备党支部",
    companyId: null,
    sex: "0",
    nation: "汉族",
    birthday: "1970-12-20",
    edu: "7",
    degree: null,
    workDep: "工程技术部",
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2006-12-07",
    formalDate: null,
    title: null,
    adminPost: "维修技术员",
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "350",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: null,
    djname: null,
    groupName: "设备党支部第二党小组",
  },
  {
    searchValue: null,
    uid: "1747125713801170945",
    creatorUid: "382",
    createTime: "2024-01-16 13:16:45",
    updaterUid: "382",
    updateTime: "2024-01-17 11:36:16",
    params: {},
    memberName: "顾帅康",
    orgId: "211",
    orgName: "引航站引航科党总支-第三党支部",
    companyId: 1,
    sex: "0",
    nation: "汉",
    birthday: "1998-02-01",
    edu: "4",
    degree: "1",
    workDep: "引航科",
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2019-06-23",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "221",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8251",
    djname: "gjdsgjds",
    groupName: "引航7班党小组",
  },
  {
    searchValue: null,
    uid: "1744572445015265282",
    creatorUid: "199",
    createTime: "2024-01-09 12:10:58",
    updaterUid: "199",
    updateTime: "2024-01-09 12:12:33",
    params: {},
    memberName: "唐建",
    orgId: "184",
    orgName: "轮驳分公司第一党支部",
    companyId: null,
    sex: "0",
    nation: "汉族",
    birthday: "1968-08-09",
    edu: "4",
    degree: null,
    workDep: "北京东路管理部",
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2000-10-27",
    formalDate: null,
    title: null,
    adminPost: "北京东路管理部副经理",
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "706",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: "2",
    partyPosition3: "2",
    djuid: null,
    djname: null,
    groupName: "北京东路党小组",
  },
  {
    searchValue: null,
    uid: "1742391668013875201",
    creatorUid: "50",
    createTime: "2024-01-03 11:45:20",
    updaterUid: "50",
    updateTime: "2024-01-03 11:45:21",
    params: {},
    memberName: "姚剑晓",
    orgId: "128",
    orgName: "盛东公司机关党支部",
    companyId: 27,
    sex: "0",
    nation: null,
    birthday: "1991-03-22",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2022-12-15",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "136",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8249",
    djname: "yjx9103",
    groupName: "第一党小组",
  },
  {
    searchValue: null,
    uid: "1742391651568009218",
    creatorUid: "50",
    createTime: "2024-01-03 11:45:16",
    updaterUid: "50",
    updateTime: "2024-01-03 11:45:17",
    params: {},
    memberName: "温鸿飞",
    orgId: "128",
    orgName: "盛东公司机关党支部",
    companyId: 27,
    sex: "1",
    nation: null,
    birthday: "1990-09-24",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2014-11-07",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: null,
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8248",
    djname: "wenhongfei",
    groupName: null,
  },
  {
    searchValue: null,
    uid: "1739440722942197761",
    creatorUid: "64",
    createTime: "2023-12-26 08:19:20",
    updaterUid: "64",
    updateTime: "2023-12-26 13:10:52",
    params: {},
    memberName: "郑毅",
    orgId: "14",
    orgName: "复兴公司深水港党总支-第二党支部",
    companyId: 4,
    sex: "0",
    nation: null,
    birthday: "1999-01-14",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2021-05-19",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "331",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8247",
    djname: "zhengyi1999",
    groupName: "第八党小组",
  },
  {
    searchValue: null,
    uid: "1736758756727947266",
    creatorUid: "275",
    createTime: "2023-12-18 22:42:10",
    updaterUid: "275",
    updateTime: "2023-12-19 13:19:07",
    params: {},
    memberName: "秦涛",
    orgId: "281",
    orgName: "工程指挥部工程党支部",
    companyId: null,
    sex: "0",
    nation: "汉",
    birthday: null,
    edu: "4",
    degree: "1",
    workDep: "工程建设指挥部",
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2005-05-27",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "97",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: null,
    djname: null,
    groupName: "第一党小组",
  },
  {
    searchValue: null,
    uid: "1736727148331368450",
    creatorUid: "59",
    createTime: "2023-12-18 20:36:34",
    updaterUid: "59",
    updateTime: "2023-12-20 10:50:57",
    params: {},
    memberName: "王伦星",
    orgId: "8",
    orgName: "复兴公司船务部党总支-张华浜区域党支部",
    companyId: 4,
    sex: "0",
    nation: "汉族",
    birthday: "1990-05-19",
    edu: "4",
    degree: "1",
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2011-11-01",
    formalDate: null,
    title: null,
    adminPost: "实习驾驶",
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "403",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8246",
    djname: "wang123456",
    groupName: "复兴公司船务部党总支张华浜区域党支部第三党小组",
  },
  {
    searchValue: null,
    uid: "1729740263392169986",
    creatorUid: "138",
    createTime: "2023-11-29 13:53:10",
    updaterUid: "0",
    updateTime: "2023-12-09 11:32:27",
    params: {},
    memberName: "袁成",
    orgId: "103",
    orgName: "上港物流上港联代党支部",
    companyId: 28,
    sex: "0",
    nation: null,
    birthday: "2000-11-12",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2021-04-26",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "279",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8240",
    djname: "yc12345",
    groupName: "第四党小组",
  },
  {
    searchValue: null,
    uid: "1727228548117041154",
    creatorUid: "423",
    createTime: "2023-11-22 15:32:31",
    updaterUid: "423",
    updateTime: "2023-11-22 15:32:31",
    params: {},
    memberName: "崔海江",
    orgId: "496",
    orgName: "海铁联运党支部",
    companyId: 44,
    sex: "0",
    nation: null,
    birthday: "1976-04-04",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2012-12-10",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "694",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8237",
    djname: "chj5199",
    groupName: "营运服务党小组",
  },
  {
    searchValue: null,
    uid: "1747471447339683842",
    creatorUid: "103",
    createTime: "2024-01-17 12:10:34",
    updaterUid: "103",
    updateTime: "2024-01-17 12:10:34",
    params: {},
    memberName: "郭明",
    orgId: "60",
    orgName: "明东公司工程技术部党总支-工程部设备党支部",
    companyId: null,
    sex: "0",
    nation: "汉族",
    birthday: "1970-12-20",
    edu: "7",
    degree: null,
    workDep: "工程技术部",
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2006-12-07",
    formalDate: null,
    title: null,
    adminPost: "维修技术员",
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "350",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: null,
    djname: null,
    groupName: "设备党支部第二党小组",
  },
  {
    searchValue: null,
    uid: "1747125713801170945",
    creatorUid: "382",
    createTime: "2024-01-16 13:16:45",
    updaterUid: "382",
    updateTime: "2024-01-17 11:36:16",
    params: {},
    memberName: "顾帅康",
    orgId: "211",
    orgName: "引航站引航科党总支-第三党支部",
    companyId: 1,
    sex: "0",
    nation: "汉",
    birthday: "1998-02-01",
    edu: "4",
    degree: "1",
    workDep: "引航科",
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2019-06-23",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "221",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8251",
    djname: "gjdsgjds",
    groupName: "引航7班党小组",
  },
  {
    searchValue: null,
    uid: "1744572445015265282",
    creatorUid: "199",
    createTime: "2024-01-09 12:10:58",
    updaterUid: "199",
    updateTime: "2024-01-09 12:12:33",
    params: {},
    memberName: "唐建",
    orgId: "184",
    orgName: "轮驳分公司第一党支部",
    companyId: null,
    sex: "0",
    nation: "汉族",
    birthday: "1968-08-09",
    edu: "4",
    degree: null,
    workDep: "北京东路管理部",
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2000-10-27",
    formalDate: null,
    title: null,
    adminPost: "北京东路管理部副经理",
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "706",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: "2",
    partyPosition3: "2",
    djuid: null,
    djname: null,
    groupName: "北京东路党小组",
  },
  {
    searchValue: null,
    uid: "1742391668013875201",
    creatorUid: "50",
    createTime: "2024-01-03 11:45:20",
    updaterUid: "50",
    updateTime: "2024-01-03 11:45:21",
    params: {},
    memberName: "姚剑晓",
    orgId: "128",
    orgName: "盛东公司机关党支部",
    companyId: 27,
    sex: "0",
    nation: null,
    birthday: "1991-03-22",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2022-12-15",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "136",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8249",
    djname: "yjx9103",
    groupName: "第一党小组",
  },
  {
    searchValue: null,
    uid: "1742391651568009218",
    creatorUid: "50",
    createTime: "2024-01-03 11:45:16",
    updaterUid: "50",
    updateTime: "2024-01-03 11:45:17",
    params: {},
    memberName: "温鸿飞",
    orgId: "128",
    orgName: "盛东公司机关党支部",
    companyId: 27,
    sex: "1",
    nation: null,
    birthday: "1990-09-24",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2014-11-07",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: null,
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8248",
    djname: "wenhongfei",
    groupName: null,
  },
  {
    searchValue: null,
    uid: "1739440722942197761",
    creatorUid: "64",
    createTime: "2023-12-26 08:19:20",
    updaterUid: "64",
    updateTime: "2023-12-26 13:10:52",
    params: {},
    memberName: "郑毅",
    orgId: "14",
    orgName: "复兴公司深水港党总支-第二党支部",
    companyId: 4,
    sex: "0",
    nation: null,
    birthday: "1999-01-14",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2021-05-19",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "331",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8247",
    djname: "zhengyi1999",
    groupName: "第八党小组",
  },
  {
    searchValue: null,
    uid: "1736758756727947266",
    creatorUid: "275",
    createTime: "2023-12-18 22:42:10",
    updaterUid: "275",
    updateTime: "2023-12-19 13:19:07",
    params: {},
    memberName: "秦涛",
    orgId: "281",
    orgName: "工程指挥部工程党支部",
    companyId: null,
    sex: "0",
    nation: "汉",
    birthday: null,
    edu: "4",
    degree: "1",
    workDep: "工程建设指挥部",
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2005-05-27",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "97",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: null,
    djname: null,
    groupName: "第一党小组",
  },
  {
    searchValue: null,
    uid: "1736727148331368450",
    creatorUid: "59",
    createTime: "2023-12-18 20:36:34",
    updaterUid: "59",
    updateTime: "2023-12-20 10:50:57",
    params: {},
    memberName: "王伦星",
    orgId: "8",
    orgName: "复兴公司船务部党总支-张华浜区域党支部",
    companyId: 4,
    sex: "0",
    nation: "汉族",
    birthday: "1990-05-19",
    edu: "4",
    degree: "1",
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2011-11-01",
    formalDate: null,
    title: null,
    adminPost: "实习驾驶",
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "403",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8246",
    djname: "wang123456",
    groupName: "复兴公司船务部党总支张华浜区域党支部第三党小组",
  },
  {
    searchValue: null,
    uid: "1729740263392169986",
    creatorUid: "138",
    createTime: "2023-11-29 13:53:10",
    updaterUid: "0",
    updateTime: "2023-12-09 11:32:27",
    params: {},
    memberName: "袁成",
    orgId: "103",
    orgName: "上港物流上港联代党支部",
    companyId: 28,
    sex: "0",
    nation: null,
    birthday: "2000-11-12",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2021-04-26",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "279",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8240",
    djname: "yc12345",
    groupName: "第四党小组",
  },
  {
    searchValue: null,
    uid: "1727228548117041154",
    creatorUid: "423",
    createTime: "2023-11-22 15:32:31",
    updaterUid: "423",
    updateTime: "2023-11-22 15:32:31",
    params: {},
    memberName: "崔海江",
    orgId: "496",
    orgName: "海铁联运党支部",
    companyId: 44,
    sex: "0",
    nation: null,
    birthday: "1976-04-04",
    edu: null,
    degree: null,
    workDep: null,
    partyPosition: "2",
    applyDate: null,
    partyLessonDate: null,
    createTableDate: null,
    trainContacts: null,
    planDevelopDate: null,
    remark: null,
    introducer: null,
    trainDate: null,
    joinDate: "2012-12-10",
    formalDate: null,
    title: null,
    adminPost: null,
    officeDate: null,
    tel: null,
    status: null,
    laborDiv: null,
    groupId: "694",
    isBranchMember: null,
    isActive: "1",
    transState: "0",
    partyPosition2: null,
    partyPosition3: null,
    djuid: "8237",
    djname: "chj5199",
    groupName: "营运服务党小组",
  },
];
const 党小组长名单 = ["test"];
const 党小组管理 = ["test"];
const 党员名册 = ["test"];
const 党员调动记录 = ["test"];
const 帮困记录 = [{ uid: "115" }];
const 谈心谈话 = [{ uid: "116" }];
const 发展党员 = [{ uid: "117" }];
const 党支部大会记录 = [{ uid: "118" }];
const 党支委会会议 = [{ uid: "119" }];
const 党小组会议 = [{ uid: "120" }];
const 党课记录 = [{ uid: "121" }];
const 主题党日 = [{ uid: "122" }];
const 支部年度工作计划 = [{ uid: "123" }];
const 支部年度工作总结 = [{ uid: "124" }];
const 党费 = [{ uid: "125" }];
const 民主生活会 = [{ uid: "126" }];
const 党员民主评议管理 = [{ uid: "127" }];

const templatex = [
  {
    uid: "1742448216295686145",
    hoster: "王婷",
    orgId: "73",
    orgName: "龙吴分公司机关党支部",
    actualDate: "2023-12-26",
    attenders: "全体出席",
    absentees: null,
    detail:
      "第一议题：学习习近平总书记考察上海重要讲话精神。\n王婷：习近平总书记亲临上海考察指导，饱含着对上海城市和上海人民的深切关爱，体现了对上海发展的信任重托，给全市上下以强大的思想指引、精神鼓舞和前进动力。\n倪秀芳：我们要学深悟透习近平总书记重要讲话精神，完整、准确、全面贯彻新发展理念。\n於小东：习近平总书记考察上海重要讲话高屋建瓴、思想深邃，内涵丰富、饱含深情，为上海下一步的发展指明了方向。这是对上海莫大的鼓励和鞭策，这也是对我们的充分信任。为此，我们进一步做好各项工作以不辜负习总书记的隐隐嘱托。\n黄震：要深刻领会习近平总书记重要讲话精神，聚焦“五个中心”重要使命，起而行之、奋发有为，秉持更强烈的自觉、更务实的举措以及更有力的行动。\n韩奕倩：认真学习与领会习总书记的讲话精神，学深悟透并认真贯彻执行，不断以更实的举措，为龙吴“四新”发展做出更积极的贡献。\n第二议题：讨论2023年度支部安全生产先进个人名单。\n王婷：根据公司安委会有关通知，2023年度机关党支部安全生产先进个人名额为1人。接下来，请各支委班子成员根据各部门酝酿推荐名单进行讨论。\n韩奕倩：根据总经理办公室部门酝酿，推荐陈永良同志。陈永良同志在2023年工作中，能够按照公务用车各项规定行使职责，并严格执行各项安全规定，确保了公司公务的各项用车安全。\n倪秀芳：同意推荐陈永良。\n於小东：同意。\n黄震：同意。\n王婷：同意上报总经理办公室陈永良为2023年安全生产先进个人。\n会议一致讨论通过上报总经理办公室陈永良为2023年度支部安全生产先进个人。\n",
    fileName: null,
    filePath: null,
    ossId: null,
  },
  {
    uid: "1740187719781416961",
    hoster: "张德年",
    orgId: "87",
    orgName: "国客中心工程技术部党支部",
    actualDate: "2023-12-27",
    attenders: "全体出席",
    absentees: "无",
    detail:
      "1、本月支委会第一议题：学习习近平在上海考察时的重要指示；\n2、要求分人落实党员办公桌上的个人承诺标识更换工作，要求每一位党员必须立即更换；\n3、12月学习宣传贯彻习近平总书记考察上海重要讲话内容沟通准备；\n4、新一届支部成员工作分解落实，明年各项工作的目标计划工作，宣读并审阅党支部年终总结报告。",
    fileName: null,
    filePath: null,
    ossId: null,
  },
  {
    uid: "1741711231083954178",
    hoster: "张正保",
    orgId: "277",
    orgName: "振东分公司工程技术部党支部",
    actualDate: "2023-12-27",
    attenders: "张正保 严俊  顾连锋 赵华",
    absentees: "何平（借调集团工程部）",
    detail:
      "1、学习习近平总书记在第十个国家宪法日作出的重要指示；2、开展第二十四次党风廉政教育月活动，查摆存在问题；同时通报主管以上管理人员述廉评价情况汇总。",
    fileName: null,
    filePath: null,
    ossId: null,
  },
  {
    uid: "1739818141477863426",
    hoster: "张中成",
    orgId: "199",
    orgName: "罗泾分公司机械运行部党支部",
    actualDate: "2023-12-27",
    attenders: "全体出席、蔡永华",
    absentees: "无",
    detail:
      "一、支委会听取季度党风廉政建设工作报告\n二、支委会听取部门工会季度工作报告\n三、支委会听取团支部工作报告\n四、季度员工队伍状况和意识形态工作分析\n\n一、支委会听取季度党风廉政建设工作报告\n张中成：四季度乃至全年来，机械运行部党支部党支部认真贯彻落实党风廉政建设，根据公司关于《沪港罗委纪发〔2023〕30号关于开展第二十四次党风廉政教育月的通知》要求，机械运行部党支部结合实际，认真开展了第二十四次党风廉政教育月活动。\n党支部现有副职以上管理人员3名，大家结合自身分管情况，对照“四责协同”机制要求，认真开展了了履职自查和述廉工作。\n具体见附件。\n李大伟：同意。\n周斌：同意。\n卜俊：同意。\n张中成：同意。\n王伟：同意。\n\n二、支委会听取部门工会季度工作报告\n张中成：四季度，机械运行部工会坚持以习近平新时代中国特色社会主义思想为指导，以职工需求为导向，认真做好班组学习、职工技能登高、季节性防寒保暖等工作。\n具体见附件。\n李大伟：同意。\n周斌：同意。\n卜俊：同意。\n张中成：同意。\n王伟：同意。\n\n三、支委会听取团支部工作报告\n蔡永华：2023年机械运行部团支部在公司团委和部门党支部的帮助和指导下，深入贯彻落实全年工作，务实创新，开拓进取，不断加强团支部的自身建设，充分发挥团员青年主力军的作用，扎实有效地开展了各项工作。\n具体见附件。\n李大伟：同意。\n周斌：同意。\n卜俊：同意。\n张中成：同意。\n王伟：同意。\n\n四、季度员工队伍状况和意识形态工作分析\n张中成：四季度，机械运行部党支部坚持以习近平新时代中国特色社会主义思想为指导，认真贯彻落实党的二十大精神以及二十大一中、二中全会精神，凝心聚力，共谋发展，坚持“一切工作到支部”、坚持“一切工作到班组、到个人”，紧紧围绕中心工作发力，截至2023年底，机械运行部党支部现有党员15名，平均年龄43.8岁，翻班党员7人。正式职工39人，劳务承包工367人，总人数406人。\n具体见附件。\n\n李大伟：同意。\n周斌：同意。\n卜俊：同意。\n张中成：同意。\n王伟：同意。\n",
    fileName: null,
    filePath: null,
    ossId: null,
  },
];
export default {
  支部情况,
  党支部委员名单,
  党小组长名单,
  党小组管理,
  党员名册,
  党员调动记录,
  帮困记录,
  谈心谈话,
  发展党员,
  党支部大会记录,
  党支委会会议,
  党小组会议,
  党课记录,
  主题党日,
  支部年度工作计划,
  支部年度工作总结,
  党费,
  民主生活会,
  党员民主评议管理,
};
